baseURL = "https://modest-haibt-9567fd.netlify.com/"
languageCode = "en-us"
title = "Timer | Responsive Multipurpose Bootstrap Hugo Template"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "春"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "ケア内容"
        url     = "/service"
        weight  = 3
    [[menu.nav]]
        name    = "ブログ"
        url     = "https://note.mu/babycareharu"
        weight  = 5
    [[menu.nav]]
        name    = "アクセス"
        url     = "/contact"
        weight  = 6

# Site Params
[params]
    home = "ホーム"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Airspace Hugo theme"
    author = "Themefisher"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "母乳育児相談室"
        description = "母乳育児相談室春では、年間300名以上のママさんのケアを行なっています。赤ちゃんが喜ぶスキンシップマッサージ、おっぱいのトラブル、ちょっとした悩みなど子育ての不安を、楽しく幸せな育児にしていくことをコンセプトに支えています。"
        btn     = true
        btnText = "Download More"
        btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "春"
        [[params.banner.flipText]]
            title   = "はる"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "助産士紹介"
        content = "1956年生まれ。1976年に沖縄県立看護学校を卒業後、1977年から３年間、琉球大学院病院に勤める。看護師時代の経験の中で、助産師になりたい気持ちが高まり、助産師の資格を取るため上京し、３年間大学に通う。その後、助産師として30年間、沖縄の現場を支え続け、2001年、独立。現在は、助産師として、年間３００人以上のママさんの相談を受けつつ、保育専門学校の非常勤講師として、育児教育を担当している。"
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "お問い合わせ"
        content = "母乳育児相談室春では、楽しく幸せな育児を支えています。お気軽にご連絡ください。"
        btnText = "問い合わせ"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "ケア内容"
        subtitle= "母乳育児相談、乳幼児育児相談、思春期・妊産婦・更年期相談、タッチケア教室、妊婦産婦操体教室、子育ての不安を、楽しく幸せな育児にをコンセプトに支えています。"

    # Feature Product Section
    [params.featureProduct]
        enable  = true
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    